//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchCheck.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameStat
    {
        public int GameId { get; set; }
        public System.DateTime CheckDate { get; set; }
        public int Viewers { get; set; }
        public int Channels { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
